AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ippt-sam

  Sample SAM Template for ippt-sam

Parameters:
  Env:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Environment of this stack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  IpptBotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "IpptBotFunction-${Env}"
      CodeUri: ippt_bot/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        IpptBot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ippt_bot
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  IpptBotApi:
    Description: "API Gateway endpoint URL for Prod stage for IPPT Bot function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ippt_bot/"
  IpptBotFunction:
    Description: "IPPT Bot Lambda Function ARN"
    Value: !GetAtt IpptBotFunction.Arn
  IpptBotFunctionIamRole:
    Description: "Implicit IAM Role created for IPPT Bot function"
    Value: !GetAtt IpptBotFunctionRole.Arn
